version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=cnc
      - MYSQL_USER=Eric
      - MYSQL_PASSWORD=0000